### ISSUE TITLE
Mask password on output

### ISSUE THREAD

**Issue by SebastianSchuetze** [ValoIntranet/doctor#48] opened 2021-02-11 08:46 UTC
When I use doctor and I choose password authentication and the service principal has not been approved yet, then the cli returns the error:

![image](https://user-images.githubusercontent.com/7256168/107616365-31948d00-6c4e-11eb-800a-c499caac0af7.png)

The problem here is, that you mask the password when you prompt for it but the output it in clear text. That is a pretty bad idea when you want to demo something and run into the error and everybody can see your password.

**Comment by estruyf** [comment] 2021-02-11 13:35
Great enhancement! Thanks for suggesting this.

**Comment by estruyf** [comment] 2021-02-11 14:19
@SebastianSchuetze seemed this was actually coming from the CLI, but the problem is fixed. The password and certificate base64 string are both masked. Thanks again for the suggestion!

This is now available for you to test in the latest beta.

**Comment by estruyf** [comment] 2021-02-12 08:26
Version `1.6.0` is released with this issue included.

**Closed by estruyf** 2021-02-12 08:26 UTC
Labels: enhancement
